name: Continuous Integration
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    # TODO: Enable me when unit test is ready
    # services:
    #   postgres:
    #     image: postgres:15.7
    #     env:
    #       POSTGRES_USER: ${{ secrets.DB_USER || 'postgres' }}
    #       POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD || 'postgres' }}
    #       POSTGRES_DB: cit-web-db-test
    #     ports:
    #       - "5433:5432"
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Needed for detecting changes

      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'npm'

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/package-lock.json', '**/turbo.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/package-lock.json', '**/turbo.json') }}-
            ${{ runner.os }}-turbo-

      - name: Install packages
        run: npm ci

      # - name: Security audit
      #   run: npm audit --production --audit-level=high || true

      - name: Code linting
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run lint

      - name: Build application
        run: npm run build

      # TODO: Enable me when unit test is ready
      # - name: Unit test
      #   run: npm run test
